name: AutoCheck IPv6

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:    
      - main
    paths:
      - 'websites.txt'
# When the event is triggered, GitHub Actions will run the jobs indicated
jobs:
  check:
    # Uses a ubuntu-lates runner to complete the requested steps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
          git config --global user.name "FledgeXu"
          git config --global user.email "xzk0701@gmail.com"
          git pull
          sudo apt-get install -y jd
          sudo chmod a+Xx test.sh
          ./test.sh
          git add -A
          git commit -m "$(date) update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
