name: AutoCheck IPv6

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
        main
# When the event is triggered, GitHub Actions will run the jobs indicated
jobs:
  check:
    # Uses a ubuntu-lates runner to complete the requested steps
    runs-on: ubuntu-latest
    steps:
    - run: |
          git config --global user.name "FledgeXu"
          git config --global user.email "xzk0701@gmail.com"
          sudo apt-get install -y jd
          pwd
          ls
          sudo chmod a+Xx test.sh
          ./test.sh
          git add -A
          git commit -m "$(date) update"
          #- name: Push changes
          #  uses: ad-m/github-push-action@master
          #  with:
          #    github_token: ${{ secrets.GITHUB_TOKEN }}
          #    branch: ${{ github.ref }}
